-- AlterTable
ALTER TABLE "AiPrediction" ADD COLUMN     "carbsG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fiberG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mealName" TEXT,
ADD COLUMN     "proteinG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalMax" DOUBLE PRECISION,
ADD COLUMN     "totalMin" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "AiPredictionItem" ADD COLUMN     "calorieMax" DOUBLE PRECISION,
ADD COLUMN     "calorieMin" DOUBLE PRECISION;
